-- 012_gamification.sql
BEGIN;
ALTER TABLE patients
  ADD COLUMN IF NOT EXISTS deby_level      INT  NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS deby_xp         INT  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS current_streak  INT  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS longest_streak  INT  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_logged_date DATE,
  ADD COLUMN IF NOT EXISTS league_name     TEXT NOT NULL DEFAULT 'Bronze',
  ADD COLUMN IF NOT EXISTS league_points   INT  NOT NULL DEFAULT 0;
COMMIT;
